### ISSUE TITLE
Mobile version correction

### ISSUE THREAD

**Issue by brettfarley** [VeritasStrategies/Poplin#8]
In the mobile version of the site, the logo and menu bar are screwed up in the spacing. Please fix and ensure that it does not mess up the spacing on the desktop version as well.

**Comment by santosh-ricom** [comment]
Done changes once check it

**Comment by brettfarley** [comment]
![img_4803](https://cloud.githubusercontent.com/assets/13319038/12724262/b4d15876-c8d2-11e5-96f2-e39f821c6d21.PNG)

**Comment by santosh-ricom** [comment]
once check it i decrease the font size

**Comment by brettfarley** [comment]
Still not fixed. See screenshot.

Brett

--sent from my iPhone
